import Head from "next/head";
import Image from "next/image";
import Layout from "../components/Layout";
import Intro from "../components/Intro";
import Services from "../components/Services";
import Testimonial from "../components/Testimonial";
import { data } from "../helpers/data";

export default function Home({ services }) {
  console.log(services);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Intro />
      <Services services={services} />
      <Testimonial />
    </div>
  );
}

//allow us to fetch data before rendering the page
export const getStaticProps = async () => {
  const services = data;
  return {
    props: { services },
  };
};
